version: '2.2'
services:
  web:
    extends:
      file: docker-compose.prod.yml
      service: web
    ports:
      - "5000:80"
  dashboard_init:
    user: ${CURRENT_UUID}
    extends:
      file: docker-compose.prod.yml
      service: dashboard_init
    image: ansible/dashboard-dev:latest
    environment:
      PYTHONUNBUFFERED: 0
    volumes:
      - "../:/dashboard_devel"
  dashboard:
    user: ${CURRENT_UUID}
    extends:
      file: docker-compose.prod.yml
      service: dashboard
    image: ansible/dashboard-dev:latest
    environment:
      PYTHONUNBUFFERED: 0
    volumes:
      - "../:/dashboard_devel"
    command: make -C /dashboard_devel/ uwsgi-dev
  dashboard_worker:
    user: ${CURRENT_UUID}
    extends:
      file: docker-compose.prod.yml
      service: dashboard_worker
    image: ansible/dashboard-dev:latest
    volumes:
      - "../:/dashboard_devel"
    links:
      - redis
  dashboard_scheduler:
    user: ${CURRENT_UUID}
    extends:
      file: docker-compose.prod.yml
      service: dashboard_scheduler
    image: ansible/dashboard-dev:latest
    volumes:
      - "../:/dashboard_devel"
    links:
      - redis
  redis:
    extends:
      file: docker-compose.prod.yml
      service: redis
